/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thesis_transcodingapp_Videokit */

#ifndef _Included_com_thesis_transcodingapp_Videokit
#define _Included_com_thesis_transcodingapp_Videokit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thesis_transcodingapp_Videokit
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thesis_transcodingapp_Videokit_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
